# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  workflow_dispatch:
  schedule:
    - cron: '28 14 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    scheduled:
      runs-on: ubuntu-latest
      steps:
      - name: check out this repo
        uses: actions/checkout@v2
      - name: Get the data and analyze
        run: sh ./aed.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        shell: bash
      - name: Commit and push if changed
        run: |-
           git config user.name "Automated"
           git config user.email "actions@users.noreply.github.com"
           git add -A
           timestamp=$(date -u)
           git commit -m "Latest data: ${timestamp}" || exit 0
           git push
